# Conclusion {-}

## Summary of results

### Part 1

Part 1 left us with some interesting results. While not all of our methods gave conclusive interpretations, we saw that (on the whole) overvoting and undervoting were related to some similar variables as voter turnout is in general. The models for turnout and undervoting had relevant variables dealing with age, education and race, which are variables commonly linked to voting habits more generally in other research. Our turnout and undervoting models seemed to agree on the direction of these correlates as well. The coefficients provided by the overvoting model were clear that precincts with high number of African-American residents were more likely to overvote (and thus lose a number of votes that were attempted to be cast).

There were some weaknesses in our models, however. The poor fit and violated assumptions of the overvoting models indicate that these results may not be entirely accurate. Our undervoting model produced some unexpected relationships between demographic variables, which we could not interpret. A better tool than these regressions may be needed to parse further into this question.

We hoped that a more clear result here would be able to better inform voter education efforts, but do not feel confident in making any recommendation as such from this study. Given that the level of overvoting is so low across the board and only spikes in a few precincts, a geographically targeted education approach might be the best solution to this issue. Another course of action may be to continue voter education efforts in line with previous research on voter turnout more generally, as these same correlates are important to rates of overvoting and undervoting.

### Part 2

In Part 2, we saw that the more informed MI methods did not change the election results, though they did sometimes decrease the winner's margin of victory. This is the same result obtained by @bernhagen_missing_2010 for a separate election. If our assumption that missing ballots are MAR is correct, this indicates that overvoting and undervoting did not impact the result of this election, though these phenomena did slightly help London Breed. When we correct for variance, our certainty that Breed always wins dramatically decreases. This is a weakness of the MI method as applied to this data: because there is no "standard error" in vote share in an election (since it's not functioning as a survey), this adjusted variance does not necessarily reflect the actual variance in our estimate.

Given the disparity in undervote levels between different precincts (and the impact of demographic factors on these undervote levels), we expected one of the models with precinct or demographic to have more of an effect on the electoral results. We thought that if the precincts had different local preferences, then the now-higher weighting of underrepresented precincts might flip the election. One possible explanation as to why this did not occur is that this disparate precinct weighting did happen and it cancelled out between different precincts on the whole, leading to Breed's continued victory. Fairvote has produced some analysis that seems to indicate regional distinctions among candidates, which could support the claim about different local preferences [@noauthor_sf_nodate; @noauthor_sf_nodate-1; @noauthor_sf_nodate-2; @noauthor_sf_nodate-3]. Additionally, as indicated in @hill_exhausted_2018, the positioning of the undervotes themselves in this election may have limited the impact of full voting, and even under full voting Breed still would have won due to this positioning. Another answer is that MI itself may not produce enough variance to meaningfully affect these election results (even if there *were* a true change in the election winner), given the large number of data points and the inherent closed loop of using the observed data to modify itself^[The same problem faced by methods like the bootstrap.]. This may be a limitation of MI, as after correcting variance with Rubin's rules there was much more potential overlap in election results ([Chapter 6](#missing-results)).

We also saw that almost half of the exhausted ballots in the final round of our original election can be explained by "voluntary" undervotes, that is voters not completing the ballot fully. This evidence complicates the claim that RCV does not produce true majorities, because the phenomenon of undervoting is not *only* a function of limited rankings imposed by the jurisdiction. Further research should be conducted into the effect of taking voluntary undervoting into account on how often we observe a non-majority in RCV elections.

## Future research ideas {#further-research}

The most apparent next course of action in this resarch is to extend to more elections and jurisdictions that use RCV. This was not accomplished in this thesis due to issues with obtaining and merging the correct geographic boundaries to obtain precinct demographic information for more than one election cycle or more than one city. The advantage of this would be to extend how general the results are, and see if the demographic characteristics and imputation methods here have similar effects in different case studies. One consideration moving forward is that this missing data imputation method may not work well in Cambridge, where there are often far fewer available data points at later rankings in the ballot data^[Voters, perhaps experiencing some dizziness at the sheer number of candidates on the ballot, quite reasonably don't usually fill in choices all the way to rank 30 or so.] than we had in this San Francisco election.

An option to address this issue in Cambridge might be using some stochastic model (instead of hot deck imputation) to predict vote preferences. If a voter's state is the candidate they ranked in slot $n$, what are the "transition probabilities" of them ranking another given candidate in slot $n + 1$? This would not be a true Markov process because it would have to include some memory to ensure that no candidate appears twice for a given voter, but the Markov chain is a useful conceptual comparison.

Another desirable task would be to obtain more accurate demographic information about the election precincts. One of the limitations of this study is the inaccuracy in precinct demographic information propagated through the areal interpolation initially performed. Perhaps a more accurate interpolation could be calculated with additional ancillary data (e.g. street or zoning data, a more granular population density metric, etc.), to avoid relying on the uniform spatial population distribution assumption that we used here. Alternatively, we could obtain better demographic information about the precincts directly by examining the voter registration file for a given jurisdiction. The information carried in these files varies by state^[Race and gender are only collected in certain states, for example.], but they generally include age and whether someone voted in a given election. That would give us more detailed demographic information about the people who voted in the election, as opposed to general precinct demographics. As with any data containing personally identifiable information, care must be taken to maintain privacy if such a file is used.

In future studies, a better model specification could be used to examine which variables are correlated with overvoting and undervoting. Notably, because overvoting is so rare, we see a significant number of precincts with 0 overvotes. A zero-inflated logistic model could be applied to further enhance the conclusions presented.

Finally, we could additionally expand the research question to include 100% voter turnout, along with no overvotes or undervotes. That would require getting an accurate count of the voting-eligible population (VEP) or voting-age population (VAP) within each precinct. There would then be no information for some voters about 1st candidate supported, so precinct and demographic information alone would need to be used to predict vote choices. Such a study would be less precise in conclusions than this one, but is in turn a more broadly applicable research question. We expect that this would have some precinct-level turnout jumps that could greater impact the election result; however, this hypothesis should be considered skeptically, as we theorized the same result would appear in this study.
