---
author: 'Jay Lee'
date: 'May 2019'
institution: 'Reed College'
division: 'Mathematics and Natural Sciences'
advisor: 'Heather Kitada Smalley'
#altadvisor: 'Your Other Advisor'
# Delete line 6 if you only have one advisor
department: 'Mathematics - Statistics'
degree: 'Bachelor of Arts'
title: 'From Interpolation to Imputation: Ballot Completion in a Ranked Choice Election'
knit: "bookdown::render_book"
site: bookdown::bookdown_site
always_allow_html: yes
output: 
  thesisdown::thesis_pdf:
    toc_depth: 2
#  thesisdown::thesis_gitbook: default
#  thesisdown::thesis_word: default
#  thesisdown::thesis_epub: default
# If you are creating a PDF you'll need to write your preliminary content here or
# use code similar to line 20 for the files.  If you are producing in a different
# format than PDF, you can delete or ignore lines 20-31 in this YAML header.
abstract: |
  `r if(knitr:::is_latex_output()) paste(readLines("00-abstract.Rmd"), collapse = '\n  ')`
# If you'd rather include the preliminary content in files instead of inline
# like below, use a command like that for the abstract above.  Note that a tab is 
# needed on the line after the |.
acknowledgements: |
  To Heather, for consistently keeping me on track to actually graduate and being a wonderful thesis advisor; \par
   \bigskip
   \noindent To Andrew, Paul G., Kristin, and Paul M., for giving me a series of good jobs and unofficially advising me over the last few years; \par
   \bigskip
   \noindent To the Reed Collegium Musicum and the Anna Men, for giving me a few hours a week to take my mind off of this and make some music; \par
   \bigskip
   \noindent To Mia, Monika, Jade, and Scottie's Gang, for each giving me a semblance of a social life and getting me off campus; \par
   \bigskip
   \noindent To my family, for not getting *too* mad at me for not calling as much as I should; \par
   \bigskip
   \noindent Thank you.
abbrevs: |
  \noindent ACS: American Community Survey \par
  \noindent BIC: Bayesian Information Criterion \par
  \noindent GIS: Geographic information system \par
  \noindent IPW: Inverse probability weighting \par
  \noindent IRV: Instant-runoff voting \par
  \noindent MAR: Missing at random \par
  \noindent MCAR: Missing completely at random \par
  \noindent MI: Multiple imputation \par
  \noindent MLE: Maximum likehood estimation \par
  \noindent MNAR / NI: Missing not at random / Non-ignorable \par
  \noindent PAC: Political action committee \par
  \noindent Q-Q: Quantile-quantile \par
  \noindent RCV: Ranked choice voting \par
  \noindent RHD: Random hot deck \par
  \noindent SE: Standard error \par
  \noindent SF: San Francisco \par
  \noindent STV: Single transferable vote \par
  \noindent VAP: Voting-age population \par
  \noindent VEP: Voting-eligible population \par
bibliography: bib/thesis.bib
# Download your specific bibliography database file and refer to it in the line above.
csl: csl/apa.csl
# Download your specific csl file and refer to it in the line above.
lot: true
lof: true
#space_between_paragraphs: true
# Delete the # at the beginning of the previous line if you'd like
# to have a blank new line between each paragraph
header-includes:
- \usepackage{placeins}
- \usepackage{caption}
- \usepackage[hyphens]{url}
- \urlstyle{same}
---

<!--
Above is the YAML (YAML Ain't Markup Language) header that includes a lot of metadata used to produce the document.  Be careful with spacing in this header!

If you'd prefer to not include a Dedication, for example, simply delete lines 17 and 18 above or add a # before them to comment them out.  If you have other LaTeX packages you would like to include, delete the # before header-includes and list the packages after hyphens on new lines.

If you'd like to include a comment that won't be produced in your resulting file enclose it in a block like this.
-->

<!--
If you receive a duplicate label error after knitting, make sure to delete the index.Rmd file and then knit again.
-->

```{r include_packages, include = FALSE}
# This chunk ensures that the thesisdown package is
# installed and loaded. This thesisdown package includes
# the template files for the thesis.
if(!require(devtools))
  install.packages("devtools", repos = "http://cran.rstudio.com")
if(!require(thesisdown))
  devtools::install_github("ismayc/thesisdown")
library(thesisdown)
knitr::opts_chunk$set(echo = FALSE, eval = TRUE, cache = TRUE)
# generally I don't want code to show up in the doc
# I'll just link to the (eventually public) thesis repository to find source code
# or put them as appendices? who knows
```

<!-- You'll need to include the order that you'd like Rmd files to appear in the _bookdown.yml file for
PDF files and also delete the # before rmd_files: there.  You'll want to not include 00(two-hyphens)prelim.Rmd
and 00-abstract.Rmd since they are handled in the YAML above differently for the PDF version.
-->

<!-- The {.unnumbered} option here means that the introduction will be "Chapter 0." You can also use {-} for no numbers
on chapters.
-->

# Introduction {.unnumbered}

This thesis investigates issues in ranked choice voting (RCV), using a 2018 mayoral election in San Francisco as our observation. It is split into two major parts, each attempting to answer a separate research question. The motivation for these research questions comes out of previous work on RCV with Matthew Yancheff and Mia Leung, advised by Professors Andrew Bray (statistics) and Paul Gronke (political science) at Reed College. Multiple times while presenting this research into RCV, we were asked what the effect would be "if everybody voted". To these now-anonymous^[Two years ago, I did not think to write down their names for this purpose.] questioners, I am grateful.

This thesis was written using the [`thesisdown`](https://github.com/ismayc/thesisdown) R Markdown template for Reed College [@ismay_thesisdown_nodate]. The computation was performed in the R programming language, with significant use of the following packages:

- [`rcv`](https://github.com/ds-elections/rcv), for tabulating the results of our ranked choice elections [@lee_rcv_2019].

- [`sf`](https://github.com/r-spatial/sf), for spatial analysis and areal interpolation [@pebesma_sf_nodate].

- [`simputation`](https://github.com/markvanderloo/simputation), for multiple imputation of our ballot data [@vanderloo_simputation_2017].

- The [`tidyverse`](https://www.tidyverse.org/), for data wrangling and visualization [@noauthor_tidyverse_nodate].

All of the data used, R code, and source documents can be found at my GitHub page: <https://github.com/jayleetx/thesis>.

## Part 1 {.unnumbered}

Chapters 1-3 investigate the demographic trends associated with the phenomena of overvoting and undervoting in RCV.
[Chapter 1](#demo-litreview) reviews the literature around RCV in general, its implementation in San Francisco, and comparisons between RCV and the more common *plurality* voting system.
[Chapter 2](#demo-methods) describes the methods used to conduct this investigation, particularly the data transformations that were required to obtain usable data.
[Chapter 3](#demo-results) details the results of the investigation, validations of the methods used, and some implications for further research.

## Part 2 {.unnumbered}

Chapters 4-6 use missing data imputation methods to simulate a situation where there were no ballot errors, particularly undervoting and undervoting.
[Chapter 4](#missing-litreview) covers the theory around missing data and a comparison of multiple possible methods to deal with this phenomenon.
[Chapter 5](#missing-methods) explains the imputation methods used in this study, as well as problems encountered along the way which had to be dealt with.
[Chapter 6](#missing-results) presents the conclusions from the analysis.

